name: Project Provisioning
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

env:
  PATH_TO_TFSCRIPT_BTP: 'infra/BTP'
  PATH_TO_TFSCRIPT_CF: 'infra/CloudFoundry'

jobs:
  create_subaccount:
    name: Create Subaccount for Project
    if: ${{ !github.event.issue.pull_request }} && contains(github.event.issue.body, 'Project Name')
    runs-on: ubuntu-latest
    steps:
#      - name: trigger approval
#        uses: trstringer/manual-approval@v1
#        with:
#          secret: ${{ github.TOKEN }}
#          approvers: lechnerc77
#          minimum-approvals: 1
#          issue-title: "Approval of new project subaccount"
#          issue-body: "Please approve or deny the request."
#          exclude-workflow-initiator-as-approver: false
#          additional-approved-words: ''
#          additional-denied-words: ''

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Issue Data
        id: extract_data
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: account_request.yml

      - name: Output Issue JSON
        id: output_issue_data
        run: |
          echo '${{ steps.extract_data.outputs.json }}' | jq '.' > local.json
          project_name=$(jq -r '."project-name"' local.json)
          echo "project-name=$project_name" >> $GITHUB_OUTPUT
          cost_center=$(jq -r '."cost-center"' local.json)
          echo "cost-center=$cost_center" >> $GITHUB_OUTPUT
          space_admin=$(jq -r '."space-admin"' local.json)
          echo "space-admin=$space_admin" >> $GITHUB_OUTPUT
          subaccount_region=$(jq -r '."subaccount-region"[0]' local.json)
          echo "subaccount-region=$subaccount_region" >> $GITHUB_OUTPUT
          subaccount_stage=$(jq -r '."subaccount-stage"[0]' local.json)
          echo "subaccount-stage=$subaccount_stage" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: latest

      - name: Init Terraform for BTP
        shell: bash
        run: |
          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} init -no-color

      - name: Terraform Apply for BTP and Store Output
        id: terraform_apply_btp
        shell: bash
        run: |
            export BTP_USERNAME=${{ secrets.BTP_USERNAME }}
            export BTP_PASSWORD=${{ secrets.BTP_PASSWORD }}
            export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
            export TF_VAR_project_name=${{ steps.output_issue_data.outputs.project-name }}
            export TF_VAR_subaccount_region=${{ steps.output_issue_data.outputs.subaccount-region }}
            export TF_VAR_subaccount_stage= ${{ steps.output_issue_data.outputs.subaccount-stage }}
            export TF_VAR_project_costcenter=${{ steps.output_issue_data.outputs.cost-center }}
            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} apply -auto-approve -no-color
            cf-api-url=$(terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} output cf_api_url) | echo "cf_api_url=$cf-api-url" >> $GITHUB_OUTPUT
            cf-org-id=$(terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} output cf_org_id) | echo "cf_org_id=$cf-org-id" >> $GITHUB_OUTPUT
            subaccount-url=$(terraform -chdir=${{ env.PATH_TO_TFSCRIPT_BTP }} output subaccount_url) | echo "subaccount_url=$subaccount-url" >> $GITHUB_OUTPUT

#      - name: Init Terraform for CF
#        shell: bash
#        run: |
#          terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} init -no-color
#
#      - name: Terraform Apply for CF and Store Output
#        id: terraform_apply_cf
#        shell: bash
#        run: |
#            export CF_USER=${{ secrets.BTP_USERNAME }}
#            export CF_PASSWORD=${{ secrets.BTP_PASSWORD }}
#            export TF_VAR_globalaccount=${{ secrets.GLOBALACCOUNT }}
#            export TF_VAR_project_name=${{ steps.output_issue_data.outputs.project-name }}
#            export TF_VAR_subaccount_stage= ${{ steps.output_issue_data.outputs.subaccount-stage }}
#            export TF_VAR_cf_org_id=${{ steps.terraform_apply_btp.outputs.cf_org_id }}
#            export TF_VAR_cf_api_url=${{ steps.terraform_apply_btp.outputs.cf_api_url }}
#            export TF_VAR_subaccount_url=${{ steps.terraform_apply_btp.outputs.subaccount_url }}
#            export TF_VAR_cf_space_admin=${{ steps.output_issue_data.outputs.space-admin }}
#            export TF_VAR_cf_space_developer=${{ steps.output_issue_data.outputs.space-admin }}
#            terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} apply -auto-approve -no-color
#            cf-space-url=$(terraform -chdir=${{ env.PATH_TO_TFSCRIPT_CF }} output cf_space_url) | echo "cf_space_url=$cf-space-url" >> $GITHUB_OUTPUT

#      - name: Add comment to issue
#        uses: peter-evans/create-or-update-comment@v4
#        with:
#          issue-number: ${{ github.event.issue.number }}
#          body: |
#            The subaccount for the project has been created successfully.
#
#            Here is the relevant information for the project team:
#
#              Subaccount URL: ${{ steps.terraform_apply_btp.outputs.subaccount_url }}
#              CF API URL: ${{ steps.terraform_apply_btp.outputs.cf_api_url }}
#              CF Space URL: ${{ steps.terraform_apply_cf.outputs.cf_space_url }}
#
#            Build some awesome stuff with it!

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            The subaccount for the project has been created successfully.

            Here is the relevant information for the project team:

              Subaccount URL: ${{ steps.terraform_apply_btp.outputs.subaccount_url }}
              CF API URL: ${{ steps.terraform_apply_btp.outputs.cf_api_url }}

            Build some awesome stuff with it!
