name: Project Provisioning
on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  create_subaccount:
    name: Create Subaccount for Project
    if: ${{ !github.event.issue.pull_request }} && contains(github.event.issue.body, 'Project Name')
    runs-on: ubuntu-latest
    steps:
      - name: trigger approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: lechnerc77
          minimum-approvals: 1
          issue-title: "Approval of new project subaccount"
          issue-body: "Please approve or deny the request."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Issue Data
        id: extract_data
        uses: issue-ops/parser@v4
        with:
          body: ${{ github.event.issue.body }}
          issue-form-template: account_request.yml

      - name: Output Issue JSON
        id: output_issue_data
        run: |
          project_name=$(jq -r '."project-name"' ${{ steps.extract_data.outputs.json }})
          echo "project-name=$project_name" >> $GITHUB_OUTPUT
          cost_center=$(jq -r '."cost-center"' ${{ steps.extract_data.outputs.json }})
          echo "cost-center=$cost_center" >> $GITHUB_OUTPUT
          space_admin=$(jq -r '."space-admin"' ${{ steps.extract_data.outputs.json }})
          echo "space-admin=$space_admin" >> $GITHUB_OUTPUT
          subaccount_region=$(jq -r '."subaccount-region"[0]' ${{ steps.extract_data.outputs.json }})
          echo "subaccount-region=$subaccount_region" >> $GITHUB_OUTPUT
          subaccount_stage=$(jq -r '."subaccount-stage"[0]' ${{ steps.extract_data.outputs.json }})
          echo "subaccount-stage=$subaccount_stage" >> $GITHUB_OUTPUT

      - name: Add comment to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Name: ${{ steps.output_issue_data.outputs.project-name }}
            Cost Center: ${{ steps.output_issue_data.outputs.cost-center }}
            Space Admin: ${{ steps.output_issue_data.outputs.space-admin }}
            Region: ${{ steps.output_issue_data.outputs.subaccount-region }}
            Stage: ${{ steps.output_issue_data.outputs.subaccount-stage }}
